### ISSUE TITLE
API for randomized tests

### ISSUE THREAD

**Issue by droundy** [asayers/easybench-rs#5]
I'd love to have a nice way to run tests that require randomization. A good use case would be to test a collection data type such as a hash set, where you want to compare algorithms.  Since handling collisions (and probability of collisions) is essential, it won't do to always use the same set of data and the same operation (e.g. insert the same value).

I think one good API would be like https://docs.rs/criterion/0.3.0/criterion/struct.Bencher.html#method.iter_batched but with a simpler API matching the other easybench functions.

**Comment by asayers** [comment]
Yes, I think this makes sense.  I'd take a PR which generalizes `bench_env` to something like

```rust
fn bench_gen_env<G, F, I, O>(gen_env: G, f: F) -> Stats where
    G: FnMut() -> I, 
    F: Fn(&mut I) -> O,
```
