### ISSUE TITLE
move lib.rs to src/lib.rs

### ISSUE THREAD

**Issue by droundy** [asayers/easybench-rs#6]
This is the only rust project I've encountered that doesn't use the standardized layout.  It's just a bit disconcerting.  Doesn't really matter, but would feel more comfortable to *not* end up looking at Cargo.toml to be sure where the code is.

**Comment by asayers** [comment]
Fair enough. This C-style layout is something I stopped doing a long time ago, and now looks weird to me too.

**Comment by asayers** [comment]
Fixed in 04c5de7deb5b2e894f13950e14a0834359efc726
